name: Rust

on:
  push:
    tags:
      - '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: jetli/wasm-pack-action@v0.4.0
      with:
        # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
        version: 'latest'
    - name: create package
      working-directory: ./chess_wasm
      run: wasm-pack build
    - name: pack package into tgz
      working-directory: ./chess_wasm
      run: wasm-pack pack
    - name: release on github
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./chess_wasm/pkg/*.tgz"
